[cpu]
cputype                = auto
cycles                 = max

[dosbox]
shell environment size = 16384
splash                 = false
startbanner            = false
time source            = local

[midi]
mididevice             = none

[mixer]
nosound                = true

[render]
aspect                 = true
scaler                 = none

[sdl]
enabledosboxkeys       = false
output                 = opengl
windowresolution       = 1080x810

[config]
break                  = off
country                = 32
dos                    = high, umb
fcbs                   = 0
files                  = 0
lastdrive              = z
device driver mcb      = false
set path               = Z:\;Z:\SYSTEM;Z:\BIN;Z:\DOS;Z:\4DOS;Z:\DEBUG;Z:\TEXTUTIL
set prompt             = $P$G

[autoexec]
ECHO OFF

MODE CON COLS=80 LINES=43
KEYB BE 437 > nul

IMGMOUNT A "~/Dos/disks/a.img" -t floppy > nul
IMGMOUNT B "~/Dos/disks/b.img" -t floppy > nul
MOUNT    C "~/Dos/disks/c"               > nul

SET B=C:\BINARIES\BORLAND
SET C=C:\BINARIES\CA
SET M=C:\BINARIES\MICROSFT
SET N=C:\BINARIES\NORTON
SET U=C:\BINARIES\UTILITY
SET V=C:\BINARIES\VOLKSWRT
SET W=C:\BINARIES\WORDPERF

SET PATH=%PATH%;%B%\TASM;%B%\TBASIC;%B%\TC;%B%\TDEBUG\;%B%\TPASCAL;%B%\TPROLOG;%M%\MASM\BIN;%M%\MSC\BIN;%M%\MSCOBOL\BIN;%M%\MSFORTRN\BIN;%M%\MSFORTRN\BINB;%M%\MSPASCAL\BIN;%M%\MSQBASIC;%C%\CLIPPER\BIN;%C%\CATOOLS\BIN;%N%\NGUIDE;%U%;%V%;%W%

SET ASMEX=%M%\MASM\SAMPLES
SET COBDIR=%M%\MSCOBOL\BIN
SET HELPFILES=%M%\MASM\HELP\*.HLP;%M%\MSC\HELP\*.HLP;%M%\MSCOBOL\HELP\*.HLP;%M%\MSFORTRN\HELP\*.HLP;
SET INCLUDE=%M%\MASM\INCLUDE;%M%\MSC\INCLUDE;%M%\MSCOBOL\SOURCE;%M%\MSFORTRN\INCLUDE;%M%\MSPASCAL\INCLUDE;%M%\MSQBASIC\INCLUDE;%C%\CLIPPER\INCLUDE;%C%\CATOOLS\INCLUDE
SET INIT=
SET LIB=%M%\MSC\LIB;%M%\MSCOBOL\LIB;%M%\MSFORTRN\LIB;%M%\MSPASCAL\LIB;%M%\MSQBASIC\LIB;%C%\CLIPPER\LIB;%C%\CATOOLS\LIB
SET OBJ=%C%\CLIPPER\OBJ;%C%\CATOOLS\OBJ
SET PLL=%C%\CLIPPER\PLL;%C%\CATOOLS\PLL
SET TMP=C:\TEMP
SET TEMP=C:\TEMP

SET B=
SET C=
SET M=
SET N=
SET U=
SET V=
SET W=

C:
